language: node_js
node_js:
  - "5.10.1"
  - "4.4.3"
  - "0.12"
  - "iojs"
notifications:
  slack: rubeniskov:I82ZGuYOEQrhl29wBbQFEdjP
install:
  - npm install -g codecov istanbul
  - npm install
script:
  - npm test
after_success:
  - codecov
