language: node_js
node_js:
  - "v6.1.0"
addons:
    code_climate:
        repo_token: 29e2002d01831dd23cfada7821ca4c971b02742fb63b56b49f5d0418585e1142
notifications:
  slack: rubeniskov:I82ZGuYOEQrhl29wBbQFEdjP#templatefy
install:
  - npm install
script:
  - npm test
